name: easy_post_v2
description: "An easy to use post(forum) package for Flutter and Firebase."
version: 0.0.3
homepage: https://github.com/thruthesky/easy_packages/tree/main/easy_post

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.2
  easy_category: ^0.0.2
  easy_comment: ^0.0.3
  easy_helpers: ^0.0.6
  easy_like: ^0.0.5
  easy_locale: ^0.0.4
  easy_storage: ^0.0.5
  easyuser: ^0.0.15
  firebase_auth: ^5.1.1
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter
  youtube: ^2.0.0
  youtube_parser: ^2.1.4
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
