name: easyuser
description: "An easy to use user management package with Firebase as backend."
version: 0.0.34
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  date_picker_v2: ^0.0.4
  easy_engine: ^0.0.4
  easy_helpers: ^0.0.14
  easy_locale: ^0.0.11
  easy_realtime_database: ^0.0.7
  easy_report: ^0.0.6
  easy_storage: ^0.0.19
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  firebase_ui_database: ^1.4.4
  flutter:
    sdk: flutter
  memory_cache: ^1.2.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easyuser
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - user
  - user-management
  - user-management-system
  - firebase
  - easy-packages
