name: example
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: 5.0.2
  cloud_functions: 5.0.2
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  easy_category: ^0.0.2
  easy_comment:
  easy_engine:
  easy_helpers:
  easy_like:
  easy_locale:
  easy_post_v2:
  easy_storage:
  easychat:
  easyuser:
  firebase_auth: 5.1.1
  firebase_core: 3.1.1
  firebase_database: 11.0.2
  firebase_messaging: 15.0.2
  firebase_storage: 12.1.0
  firebase_ui_firestore: ^1.6.4
  firebase_vertexai: ^0.2.2+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.0
  integration_test:
    sdk: flutter
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.3
  phone_sign_in: ^0.0.7
  record: ^5.1.2
  social_design_system: ^0.0.19
  web: ^0.5.1

dependency_overrides:
  easy_comment:
    path: ../easy_comment
  easy_engine:
    path: ../easy_engine
  easy_post_v2:
    path: ../easy_post
  easy_helpers:
    path: ../easy_helpers
  easy_like:
    path: ../easy_like
  easy_locale:
    path: ../easy_locale
  easy_storage:
    path: ../easy_storage
  easychat:
    path: ../easychat
  easyuser:
    path: ../easyuser

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
