name: easychat
description: "Full featured and complete chat package for Flutter and Firebase"
version: 0.0.12
homepage: https://github.com/thruthesky/easy-packages

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.2
  easy_helpers: ^0.0.11
  easy_locale: ^0.0.8
  easy_report: ^0.0.2
  easy_storage: ^0.0.13
  easyuser: ^0.0.22
  firebase_auth: ^5.1.1
  firebase_database: ^11.0.2
  firebase_ui_database: ^1.4.4
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

repository: https://github.com/thruthesky/easy-packages/main/tree/easychat
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - chat
  - chat-room
  - chat-ui
  - firebase
  - easy-packages
