name: easy_like
description: "An esay way to handle the like functionality for every use case"
version: 0.0.7
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

repository: https://github.com/thruthesky/easy-packages/main/tree/easy_like
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - firebase
  - like
  - dislike
  - forum
  - easy-packages
