name: easy_phone_sign_in
description: "Phone number sign-in package for easy phone sign-in with firebase auth."
version: 0.0.16
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  country_picker: ^2.0.26
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_phone_sign_in
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - phone-sign-in
  - auth
  - sign-in
  - firebase-auth
  - easy-packages
