name: easy_report
description: "An easy report management system for various type of data for Flutter and Firebase"
version: 0.0.7
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  easy_helpers: ^0.0.14
  easy_locale: ^0.0.11
  easy_realtime_database: ^0.0.7
  easyuser: ^0.0.32
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  firebase_ui_database: ^1.4.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_report
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - report
  - report-management
  - social
  - firebase
  - easy-packages
