name: easy_report
description: "An easy report management system for various type of data for Flutter and Firebase"
version: 0.0.4
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  easy_helpers: ^0.0.11
  easy_locale: ^0.0.11
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_database: ^11.0.2
  firebase_ui_database: ^1.4.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_report
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - report
  - report-management
  - social
  - firebase
  - easy-packages
