name: easy_engine
description: "The counter part of the easy_engine project."
version: 0.0.5
homepage: https://github.com/thruthesky/easy_packages/

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_functions: ^5.1.2
  firebase_auth: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_engine
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - firebase
  - cloud-functions
  - functions
  - push-notifications
  - easy-packages
