name: easy_user_group
description: "An easy to use user group management package with Firebase as backend."
version: 0.0.1
homepage: https://github.com/thruthesky/easy_packages/

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.4.2
  easy_helpers: ^0.0.11
  easy_locale: ^0.0.11
  easy_storage: ^0.0.12
  easyuser: ^0.0.26
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_storage: ^12.3.1
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_user_group
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - user
  - user-management
  - user-management-system
  - firebase
  - easy-packages
