name: easy_design_system
description: "Elegant and easy-to-use UI/UX design library for Flutter, crafted to enhance your app's aesthetics and user experience."
version: 0.0.27
homepage: https://github.com/thruthesky/easy_packages/
environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  loop_page_view: ^1.2.5
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_design_system
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - design-system
  - widgets
  - theme
  - design
  - easy-packages
