name: easy_storage
description: "File upload package for Firebase Storage. Supports photo, video, and other files."
version: 0.0.16
homepage: https://github.com/thruthesky/easy_packages

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  easy_helpers: ^0.0.11
  easy_locale: ^0.0.11
  file_picker: ^8.0.6
  firebase_auth: ^5.3.0
  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  firebase_storage: ^12.3.1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

repository: https://github.com/thruthesky/easy_packages/tree/main/easy_storage
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - firebase
  - storage
  - upload
  - photo-upload
  - easy-packages
