name: easy_storage
description: "File upload package for Firebase Storage. Supports photo, video, and other files."
version: 0.0.11
homepage: https://github.com/thruthesky/easy_frame/tree/main/easy_storage

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.2
  easy_helpers: ^0.0.9
  easy_locale: ^0.0.6
  file_picker: ^8.0.6
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  photo_view: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

flutter:
