name: easy_storage
description: "Storage package for easy upload into Firebase"
version: 0.0.3
homepage: https://github.com/thruthesky/easy_frame/tree/main/easy_storage

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  cloud_firestore: ^5.0.2
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
