name: easy_setting_v2
description: "Easy setting management. It provides UI widgets and logics that work on Firestore"
version: 0.0.3
homepage: https://github.com/thruthesky/easy-packages

environment:
  sdk: ">=3.4.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  easy_firestore: ^0.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

repository: https://github.com/thruthesky/easy-packages/main/tree/easy_setting
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - settings
  - configs
  - firebase
  - user-settings
  - easy-packages
