name: easy_helpers
description: "Provides helper classes, functions, and extensions for easy to build flutter apps."
version: 0.0.13
homepage: https://github.com/thruthesky/easy_frame

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  devicelocale: ^0.7.1
  easy_locale: ^0.0.11
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: ^1.25.2

repository: https://github.com/thruthesky/easy-packages/tree/main/easy_helpers
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - extensions
  - flutter-extensions
  - utility
  - string-extensions
  - easy-packages
