name: easy_url_preview
description: "Helps to get and display the url preview"
version: 0.0.4
homepage: https://github.com/thruthesky/easy-packages

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # This version works with firebsae_core_web 0.5.1
  cached_network_image: ^3.3.1
  url_launcher: ^6.3.0
  html: ^0.15.4
  http: ^1.2.2
  linkify: ^5.0.0
  shared_preferences: ^2.3.2
  crypto: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

repository: https://github.com/thruthesky/easy-packages/main/tree/easy_url_preview
issue_tracker: https://github.com/thruthesky/easy_packages/issues
topics:
  - url-preview
  - site-preview
  - web
  - html
  - easy-packages
